apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qvq8qj1yc-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qvq8qj1yc-python 
  name: qvq8qj1yc-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qvq8qj1yc-python 
